version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    depends_on:
      - db
      - storage

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    env_file:
      - .env
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  storage:
    image: ghcr.io/achtungsoftware/alarik:latest
    container_name: storage
    restart: unless-stopped
    ports:
      - "${STORAGE_API_PORT}:8080"
    environment:
      - API_BASE_URL=${STORAGE_API_BASE_URL}
      - CONSOLE_BASE_URL=${STORAGE_CONSOLE_BASE_URL}
      - ADMIN_USERNAME=${STORAGE_ACCESS_KEY}
      - ADMIN_PASSWORD=${STORAGE_SECRET_KEY}
      - JWT=${JWT_SECRET}
      - ALLOW_ACCOUNT_CREATION=${ALARIK_ALLOW_ACCOUNT_CREATION}
    volumes:
      - storage_data:/app/Storage

  storage-console:
    image: ghcr.io/achtungsoftware/alarik-console:latest
    container_name: storage-console
    restart: unless-stopped
    ports:
      - "${STORAGE_CONSOLE_PORT}:3000"
    environment:
      - NUXT_PUBLIC_API_BASE_URL=${STORAGE_API_BASE_URL}
      - NUXT_PUBLIC_CONSOLE_BASE_URL=${STORAGE_CONSOLE_BASE_URL}
      - NUXT_PUBLIC_ALLOW_ACCOUNT_CREATION=${ALARIK_ALLOW_ACCOUNT_CREATION}
    depends_on:
      - storage

volumes:
  db_data:
  storage_data: