spring.application.name=01Blog

# Server Configuration
server.port=${BACKEND_PORT}

# Throw a NoHandlerFoundException when no controller matches a request.
# This allows your GlobalException handler to return a JSON 404 instead of a default HTML page.
spring.mvc.throw-exception-if-no-handler-found=true

# Disable automatic mapping of static resources by Spring Web MVC.
# Ensures that unknown paths like /api/auth/ don't get treated as static resources.
spring.web.resources.add-mappings=false


# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false


# S3-Compatible Storage
storage.internal-endpoint=${STORAGE_INTERNAL_ENDPOINT}
storage.public-endpoint=${STORAGE_PUBLIC_ENDPOINT:http://localhost:9000}
storage.access-key=${STORAGE_ACCESS_KEY}
storage.secret-key=${STORAGE_SECRET_KEY}
storage.bucket=${STORAGE_BUCKET}
storage.region=${STORAGE_REGION:us-east-1}


# Increase upload limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


# Disable security for now
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# JWT Secret
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}