spring.application.name=01Blog

# Server Configuration
server.port=${BACKEND_PORT}

# Throw a NoHandlerFoundException when no controller matches a request.
# This allows your GlobalException handler to return a JSON 404 instead of a default HTML page.
spring.mvc.throw-exception-if-no-handler-found=true

# Disable automatic mapping of static resources by Spring Web MVC.
# Ensures that unknown paths like /api/auth/ don’t get treated as static resources.
spring.web.resources.add-mappings=false


# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# MinIo Configuration
minio.url=http://minio:${MINIO_PORT}
minio.url.internal=http://minio:${MINIO_PORT}
minio.url.external=http://localhost:${MINIO_PORT}
minio.access-key=${MINIO_ROOT_USER}
minio.secret-key=${MINIO_ROOT_PASSWORD}
minio.bucket=${MINIO_BUCKET}

# Increase upload limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


# Disable security for now
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# JWT Secret
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
